version: 1
update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "live"
    automerged_updates:
    - match: {dependency_type: "all", update_type: "all"}
      Supported dependency types:
      - "all"
      Supported updates to automerge:
      - "all"